name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 20.x
  YARN_VERSION: 3.x

jobs:
  build:
    name: Lint and build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Use Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: yarn
        cache-dependency-path: yarn.lock
    - name: Use Yarn ${{ env.YARN_VERSION }}
      run: corepack use yarn@${{ env.YARN_VERSION }}
    - name: Install dependencies
      run: yarn install --immutable
    - name: Run ESLint
      run: yarn lint
    - name: Build packages
      run: yarn build
